export const venuesArray = [
    {
        id: 1,
        name: "Jives",
        location: "UNN",
        state: "Enugu",
        imageUrl: "dist/images/groove-venue.jpg",
        status: 1,
    },
    {
        id: 2,
        name: "Jives",
        location: "UNN",
        state: "Enugu",
        imageUrl: "dist/images/groove-venue.jpg",
        status: 0,
    },
    {
        id: 3,
        name: "Jives",
        location: "UNN",
        state: "Enugu",
        imageUrl: "dist/images/groove-venue.jpg",
        status: 1,
    },
    {
        id: 4,
        name: "Jives",
        location: "UNN",
        state: "Enugu",
        imageUrl: "dist/images/groove-venue.jpg",
        status: 1,
    },
    {
        id: 5,
        name: "Jives",
        location: "UNN",
        state: "Enugu",
        imageUrl: "dist/images/groove-venue.jpg",
        status: 0,
    },
    {
        id: 6,
        name: "Jives",
        location: "UNN",
        state: "Enugu",
        imageUrl: "dist/images/groove-venue.jpg",
        status: 1,
    },
    {
        id: 7,
        name: "Jives",
        location: "UNN",
        state: "Enugu",
        imageUrl: "dist/images/groove-venue.jpg",
        status: 1,
    },
    {
        id: 8,
        name: "Jives",
        location: "UNN",
        state: "Enugu",
        imageUrl: "dist/images/groove-venue.jpg",
        status: 1,
    },
    {
        id: 9,
        name: "Jives",
        location: "UNN",
        state: "Enugu",
        imageUrl: "dist/images/groove-venue.jpg",
        status: 1,
    },
    {
        id: 10,
        name: "Jives",
        location: "UNN",
        state: "Enugu",
        imageUrl: "dist/images/groove-venue.jpg",
        status: 1,
    },
    {
        id: 11,
        name: "Jives",
        location: "UNN",
        state: "Enugu",
        imageUrl: "dist/images/groove-venue.jpg",
        status: 1,
    },
    {
        id: 12,
        name: "Jives",
        location: "UNN",
        state: "Enugu",
        imageUrl: "dist/images/groove-venue.jpg",
        status: 1,
    },
    {
        id: 13,
        name: "Jives",
        location: "UNN",
        state: "Enugu",
        imageUrl: "dist/images/groove-venue.jpg",
        status: 1,
    },
    {
        id: 14,
        name: "Jives",
        location: "UNN",
        state: "Enugu",
        imageUrl: "dist/images/groove-venue.jpg",
        status: 1,
    },
    {
        id: 15,
        name: "Jives",
        location: "UNN",
        state: "Enugu",
        imageUrl: "dist/images/groove-venue.jpg",
        status: 1,
    },
    {
        id: 16,
        name: "Havila Events Centre",
        location: "Yaba",
        state: "Lagos",
        imageUrl: "dist/images/groove-venue.jpg",
        status: 0,
    },
    {
        id: 17,
        name: "Jives",
        location: "UNN",
        state: "Enugu",
        imageUrl: "dist/images/groove-venue.jpg",
        status: 1,
    },
    {
        id: 18,
        name: "Jives",
        location: "UNN",
        state: "Enugu",
        imageUrl: "dist/images/groove-venue.jpg",
        status: 1,
    },
    {
        id: 19,
        name: "Jives",
        location: "UNN",
        state: "Enugu",
        imageUrl: "dist/images/groove-venue.jpg",
        status: 1,
    },
    {
        id: 20,
        name: "Jives",
        location: "UNN",
        state: "Enugu",
        imageUrl: "dist/images/groove-venue.jpg",
        status: 1,
    },
    {
        id: 21,
        name: "Jives",
        location: "UNN",
        state: "Enugu",
        imageUrl: "dist/images/groove-venue.jpg",
        status: 1,
    },
    {
        id: 22,
        name: "Jives",
        location: "UNN",
        state: "Enugu",
        imageUrl: "dist/images/groove-venue.jpg",
        status: 1,
    },
    {
        id: 23,
        name: "Jives",
        location: "UNN",
        state: "Enugu",
        imageUrl: "dist/images/groove-venue.jpg",
        status: 1,
    },
    {
        id: 24,
        name: "Jives",
        location: "UNN",
        state: "Enugu",
        imageUrl: "dist/images/groove-venue.jpg",
        status: 1,
    },
    {
        id: 25,
        name: "Jives",
        location: "UNN",
        state: "Enugu",
        imageUrl: "dist/images/groove-venue.jpg",
        status: 1,
    },
    {
        id: 26,
        name: "Jives",
        location: "UNN",
        state: "Enugu",
        imageUrl: "dist/images/groove-venue.jpg",
        status: 1,
    },
    {
        id: 27,
        name: "Jives",
        location: "UNN",
        state: "Enugu",
        imageUrl: "dist/images/groove-venue.jpg",
        status: 1,
    },
    {
        id: 28,
        name: "Jives",
        location: "UNN",
        state: "Enugu",
        imageUrl: "dist/images/groove-venue.jpg",
        status: 1,
    },
    {
        id: 29,
        name: "Jives",
        location: "UNN",
        state: "Enugu",
        imageUrl: "dist/images/groove-venue.jpg",
        status: 1,
    },
    {
        id: 30,
        name: "Jives",
        location: "UNN",
        state: "Enugu",
        imageUrl: "dist/images/groove-venue.jpg",
        status: 1,
    },
]